#ifndef PH4NTXM_PACKET_TRANSFORMATION_ENGINE_SHARED_H
#define PH4NTXM_PACKET_TRANSFORMATION_ENGINE_SHARED_H

#include <linux/types.h>

#define PH4NTXM_PACKET_TRANSFORMATION_ENGINE_CONFIG_MAGIC 0x50544547U
#define PH4NTXM_PACKET_TRANSFORMATION_ENGINE_PROVENANCE_MARK 0x50544531U
#define PH4NTXM_PACKET_TRANSFORMATION_ENGINE_MODE_LINUX 0U
#define PH4NTXM_PACKET_TRANSFORMATION_ENGINE_MODE_WINDOWS 1U
#define PH4NTXM_PACKET_TRANSFORMATION_ENGINE_HOSTNAME_MAX 32U

enum ph4ntxm_packet_transformation_engine_drop_reason {
    PACKET_TRANSFORMATION_ENGINE_DROP_CONFIGURATION = 0,
    PACKET_TRANSFORMATION_ENGINE_DROP_SOURCE_MAC = 1,
    PACKET_TRANSFORMATION_ENGINE_DROP_VLAN = 2,
    PACKET_TRANSFORMATION_ENGINE_DROP_MARKED_LAYOUT = 3,
    PACKET_TRANSFORMATION_ENGINE_DROP_UNEXPECTED_MARK = 4,
    PACKET_TRANSFORMATION_ENGINE_DROP_ARP_LAYOUT = 5,
    PACKET_TRANSFORMATION_ENGINE_DROP_ARP_HEADER = 6,
    PACKET_TRANSFORMATION_ENGINE_DROP_ARP_SOURCE = 7,
    PACKET_TRANSFORMATION_ENGINE_DROP_ARP_TARGET = 8,
    PACKET_TRANSFORMATION_ENGINE_DROP_EAPOL = 9,
    PACKET_TRANSFORMATION_ENGINE_DROP_RAW_IP = 10,
    PACKET_TRANSFORMATION_ENGINE_DROP_OTHER_PROTOCOL = 11,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_IPV4 = 12,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_UDP = 13,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_BOOTP = 14,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_CLIENT = 15,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_RESERVED = 16,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_ADDRESSES = 17,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_OPTIONS = 18,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_ROUTE = 19,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_STORE = 20,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_IPV4_LAYOUT = 21,
    PACKET_TRANSFORMATION_ENGINE_DROP_DHCP_IPV4_CHECKSUM = 22,
    PACKET_TRANSFORMATION_ENGINE_DROP_REASON_COUNT = 23,
};

struct ph4ntxm_packet_transformation_engine_guard_config {
    __u32 magic;
    __u32 ifindex;
    __u8 mode;
    __u8 mac[6];
    __u8 hostname_length;
    __u8 hostname[PH4NTXM_PACKET_TRANSFORMATION_ENGINE_HOSTNAME_MAX];
};

#endif
