[Seat:*]
autologin-user=ph4ntxm
autologin-user-timeout=0
allow-guest=false
display-setup-script=/usr/local/sbin/ph4ntxm-session-password
session-setup-script=/usr/local/sbin/ph4ntxm-session-status auth-ready
