d /run/ph4ntxm 0755 root root -
d /run/ph4ntxm/tray 0755 root root -
f /run/ph4ntxm/tray/identity.lock 0644 root root -
f /run/ph4ntxm/tray/lockdown.lock 0644 root root -
f /run/ph4ntxm/tray/panic-button.lock 0644 root root -
