[Unit]
Requires=ph4ntxm-unbound-randomization.service
After=ph4ntxm-unbound-randomization.service network-online.target
ConditionPathExists=/run/ph4ntxm/mode-normal

[Service]
Restart=on-failure
RestartSec=2s
