[greeter]
background=/usr/share/backgrounds/ph4ntxm-abyss-login.png
logo=/usr/share/backgrounds/ph4ntxm-logo.png
theme-name=PH4NTXM-Abyss
icon-theme-name=Lyra-blue-dark
font-name=Sans 11
xft-antialias=true
xft-hintstyle=hintfull
xft-rgba=rgb
show-manual-login=false
show-remote-login=false
show-user-image=true
default-user-image=/usr/share/backgrounds/ph4ntxm-logo.png
