backend = "glx";
vsync = false;

corner-radius = 16;

shadow = false;

opacity-rule = [
    "95:window_type = 'normal' && !fullscreen"
    " && class_g != 'Xfce4-terminal'"
    " && !(class_g ?= 'firefox' || class_g ?= 'firefox-esr' || class_g ?= 'Tor Browser')"
    " && !(class_g ?= 'ristretto' || class_g ?= 'parole')"
    " && name != 'PH4NTXM Image Viewer'"
    " && name != 'PH4NTXM Media Player'"
    " && name != 'PH4NTXM Document Airlock'"
];

blur-method = "dual_kawase";
blur-strength = 2;
blur-background = true;
blur-background-frame = false;

blur-background-exclude = [
    "window_type = 'menu'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'tooltip'",
    "window_type = 'combo'"
];

rounded-corners-exclude = [
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'desktop'",
    "window_type = 'tooltip'",
    "window_type = 'dock'"
];