vsync = false;

corner-radius = 16;

shadow = false;

opacity-rule = [
    "99:window_type = 'normal' && class_g != 'Xfce4-terminal'"
];

blur-background = false;
blur-background-frame = false;

rounded-corners-exclude = [
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'",
    "window_type = 'desktop'",
    "window_type = 'tooltip'",
    "window_type = 'dock'"
];