[Icon Theme]
Name=Lyra-blue-dark
Comment=MacOSX style icon theme for linux.
Inherits=Adwaita,hicolor
Example=folder

Directories=actions/16,actions/22,actions/24,actions/scalable,actions/symbolic,animations/16,animations/22,animations/24,apps/scalable,apps/symbolic,categories/32,categories/symbolic,places/symbolic,places/48,places/16,places/22,places/24,mimes/48,mimes/symbolic,devices/scalable,devices/symbolic,devices/16,devices/22,devices/24,emblems/16,emblems/22,emblems/24,emblems/symbolic,status/16,status/22,status/24,status/32,status/symbolic

[actions/16]
Size=16
Context=Actions
Type=Fixed

[actions/22]
Size=22
Context=Actions
Type=Fixed

[actions/24]
Size=24
Context=Actions
Type=Fixed

[actions/scalable]
Size=48
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[actions/symbolic]
Size=16
Context=Actions
MinSize=16
MaxSize=512
Type=Scalable

[animations/16]
Size=16
Context=Animations
Type=Fixed

[animations/22]
Size=22
Context=Animations
Type=Fixed

[animations/24]
Size=24
Context=Animations
Type=Fixed

[apps/scalable]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[apps/symbolic]
Size=16
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[categories/32]
Size=32
Context=Categories
Type=Scalable
MinSize=32
MaxSize=256

[categories/symbolic]
Size=16
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/22]
Size=22
Context=Devices
Type=Fixed

[devices/24]
Size=24
Context=Devices
Type=Fixed

[devices/scalable]
Size=64
Context=Devices
MinSize=22
MaxSize=512
Type=Scalable

[devices/symbolic]
Size=16
Context=Devices
MinSize=16
MaxSize=512
Type=Scalable

[emblems/16]
Size=16
Context=Emblems
Type=Fixed

[emblems/22]
Size=22
Context=Emblems
MinSize=16
MaxSize=96
Type=Scalable

[emblems/24]
Size=24
Context=Emblems
Type=Fixed

[emblems/symbolic]
Size=16
Context=Emblems
MinSize=16
MaxSize=96
Type=Scalable

[mimes/48]
Size=48
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

[mimes/symbolic]
Size=16
Context=MimeTypes
MinSize=16
MaxSize=512
Type=Scalable

[places/16]
Size=16
Context=Places
Type=Fixed

[places/22]
Size=22
Context=Places
Type=Fixed

[places/24]
Size=24
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
MinSize=22
MaxSize=512
Type=Scalable

[places/symbolic]
Size=16
Context=Places
MinSize=16
MaxSize=512
Type=Scalable

[status/16]
Size=16
Context=Status
Type=Fixed

[status/22]
Size=22
Context=Status
Type=Fixed

[status/24]
Size=24
Context=Status
Type=Fixed

[status/32]
Size=32
Context=Status
MinSize=32
MaxSize=512
Type=Scalable

[status/symbolic]
Size=16
Context=Status
MinSize=16
MaxSize=512
Type=Scalable