[main]
plugins=keyfile
dhcp=dhclient
dns=none

[device]
wifi.scan-rand-mac-address=yes

[connection-ph4ntxm-preserve-mac]
ethernet.cloned-mac-address=preserve
wifi.cloned-mac-address=preserve

[connectivity]
enabled=false
interval=0

[ifupdown]
managed=true
